version: '3.9'
services:
  db-user:
    build: postgresqluser
    image: postgresqluser:1.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: user
    networks:
      - fitness_ntwrk

  db-product:
    build: postgresqlproduct
    image: postgresqlproduct:1.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: product
    networks:
      - fitness_ntwrk

  db-audit:
    build: postgresqlaudit
    image: postgresqlaudit:1.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: audit
    networks:
      - fitness_ntwrk

  pgadmin:
    build: pgadmin
    image: fitness_pgadmin:1.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "82:80"
    networks:
      - fitness_ntwrk

  swagger-ui:
    build: swagger-ui
    image: fitness_swagger-ui:1.0
    ports:
      - "81:8080"
    networks:
      - fitness_ntwrk

  product-service:
    build: product-service
    image: fitness_product-service:1.0
    networks:
      - fitness_ntwrk

  user-service:
    build: user-service
    image: fitness_user-service:1.0
    networks:
      - fitness_ntwrk

  audit-service:
    build: audit-service
    image: fitness_audit-service:1.0
    networks:
      - fitness_ntwrk

  email-service:
    build: email-service
    image: fitness_email-service:1.0
    networks:
      - fitness_ntwrk

  proxy:
    build: proxy
    image: fitness_proxy:1.0
    ports:
      - "80:80"
    networks:
      - fitness_ntwrk

networks:
  fitness_ntwrk:
    name: fitness_ntwrk