spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db-audit:5432/audit
    # url: jdbc:postgresql://localhost:5432/fitnessAudit
    username: postgres
    password: 12345
    # password: 2505573
