mail:
  host: smtp.mail.ru
  port: 465
  username: qwertyuikscldsfbsjhdv@mail.ru
  password: wCsLnzkU32i9NHRm8kzE
properties:
  mail:
    smtp:
      starttls:
        enable: true
        required: true
      auth: true
      ssl:
        trust:smtp.mail.ru