mail:
  host: smtp.mail.ru
  port: 465
  username: alsha.alsha.23@mail.ru
  password: CGtwWNqerZXfEYbM2Hyq
properties:
  mail:
    smtp:
      starttls:
        enable: true
        required: true
      auth: true
      ssl:
        trust:smtp.mail.ru